FROM python:3.8-slim

ARG MONGODB_PASSWORD

ENV AIRFLOW_HOME=~/airflow
ENV AIRFLOW_VERSION=2.5.0
ENV PYTHON=3.8

ENV CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON}.txt"

ENV MONGODB_PASSWORD=$MONGODB_PASSWORD

COPY requirements.txt /opt/cartola/requirements.txt

RUN python -m pip install --upgrade pip
RUN pip install "apache-airflow==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"
RUN pip install -r /opt/cartola/requirements.txt

COPY airflow_cartola/dag_cartola_main.py /root/airflow/dags/

COPY cartola_requests /root/airflow/dags/cartola_requests/
COPY airflow_cartola/cartola_tasks /root/airflow/dags/cartola_tasks/

EXPOSE 8080

CMD ["airflow", "standalone"]

# https://airflow.apache.org/docs/apache-airflow/stable/tutorial/taskflow.html